// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  | NewsListSlice
  | GradientSlice
  | PeopleListSlice
  | FullWidthTextSlice
  | TitleButtonSlice
  | FullWidthImageTextButtonSlice
  | FullWidthImageSlice;

/**
 * Content for Accueil documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Accueil document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *FullWidthImage → Default → Primary*
 */
export interface FullWidthImageSliceDefaultPrimary {
  /**
   * Image field in *FullWidthImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image mobile (facultatif) field in *FullWidthImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image.default.primary.mobile_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mobile_image: prismic.ImageField<never>;
}

/**
 * Default variation for FullWidthImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullWidthImage*
 */
type FullWidthImageSliceVariation = FullWidthImageSliceDefault;

/**
 * FullWidthImage Shared Slice
 *
 * - **API ID**: `full_width_image`
 * - **Description**: FullWidthImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthImageSlice = prismic.SharedSlice<
  "full_width_image",
  FullWidthImageSliceVariation
>;

/**
 * Primary content in *FullWidthImageTextButton → Default → Primary*
 */
export interface FullWidthImageTextButtonSliceDefaultPrimary {
  /**
   * Image field in *FullWidthImageTextButton → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image_text_button.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image mobile (facultatif) field in *FullWidthImageTextButton → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image_text_button.default.primary.mobile_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mobile_image: prismic.ImageField<never>;

  /**
   * Titre field in *FullWidthImageTextButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image_text_button.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Texte field in *FullWidthImageTextButton → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image_text_button.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Lien field in *FullWidthImageTextButton → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image_text_button.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for FullWidthImageTextButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthImageTextButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthImageTextButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullWidthImageTextButton*
 */
type FullWidthImageTextButtonSliceVariation =
  FullWidthImageTextButtonSliceDefault;

/**
 * FullWidthImageTextButton Shared Slice
 *
 * - **API ID**: `full_width_image_text_button`
 * - **Description**: FullWidthImageTextButton
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthImageTextButtonSlice = prismic.SharedSlice<
  "full_width_image_text_button",
  FullWidthImageTextButtonSliceVariation
>;

/**
 * Primary content in *FullWidthText → Default → Primary*
 */
export interface FullWidthTextSliceDefaultPrimary {
  /**
   * Titre field in *FullWidthText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Texte field in *FullWidthText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for FullWidthText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullWidthText*
 */
type FullWidthTextSliceVariation = FullWidthTextSliceDefault;

/**
 * FullWidthText Shared Slice
 *
 * - **API ID**: `full_width_text`
 * - **Description**: FullWidthText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthTextSlice = prismic.SharedSlice<
  "full_width_text",
  FullWidthTextSliceVariation
>;

/**
 * Primary content in *Gradient → Default → Primary*
 */
export interface GradientSliceDefaultPrimary {
  /**
   * Dégradé field in *Gradient → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient.default.primary.gradient
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gradient: prismic.ImageField<never>;
}

/**
 * Default variation for Gradient Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GradientSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GradientSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gradient*
 */
type GradientSliceVariation = GradientSliceDefault;

/**
 * Gradient Shared Slice
 *
 * - **API ID**: `gradient`
 * - **Description**: Gradient
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GradientSlice = prismic.SharedSlice<
  "gradient",
  GradientSliceVariation
>;

/**
 * Item in *NewsList → Default → Primary → Actualités*
 */
export interface NewsListSliceDefaultPrimaryNewsItem {
  /**
   * Titre field in *NewsList → Default → Primary → Actualités*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_list.default.primary.news[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *NewsList → Default → Primary → Actualités*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_list.default.primary.news[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Date field in *NewsList → Default → Primary → Actualités*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: news_list.default.primary.news[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Texte field in *NewsList → Default → Primary → Actualités*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_list.default.primary.news[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *NewsList → Default → Primary*
 */
export interface NewsListSliceDefaultPrimary {
  /**
   * Titre field in *NewsList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Actualités field in *NewsList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_list.default.primary.news[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  news: prismic.GroupField<Simplify<NewsListSliceDefaultPrimaryNewsItem>>;
}

/**
 * Default variation for NewsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsList*
 */
type NewsListSliceVariation = NewsListSliceDefault;

/**
 * NewsList Shared Slice
 *
 * - **API ID**: `news_list`
 * - **Description**: NewsList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsListSlice = prismic.SharedSlice<
  "news_list",
  NewsListSliceVariation
>;

/**
 * Item in *PeopleList → Default → Primary → Personnes*
 */
export interface PeopleListSliceDefaultPrimaryPeoplesItem {
  /**
   * Nom field in *PeopleList → Default → Primary → Personnes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_list.default.primary.peoples[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *PeopleList → Default → Primary → Personnes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: people_list.default.primary.peoples[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titre field in *PeopleList → Default → Primary → Personnes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_list.default.primary.peoples[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Texte field in *PeopleList → Default → Primary → Personnes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_list.default.primary.peoples[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *PeopleList → Default → Primary*
 */
export interface PeopleListSliceDefaultPrimary {
  /**
   * Personnes field in *PeopleList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: people_list.default.primary.peoples[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  peoples: prismic.GroupField<
    Simplify<PeopleListSliceDefaultPrimaryPeoplesItem>
  >;
}

/**
 * Default variation for PeopleList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PeopleListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PeopleListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PeopleList*
 */
type PeopleListSliceVariation = PeopleListSliceDefault;

/**
 * PeopleList Shared Slice
 *
 * - **API ID**: `people_list`
 * - **Description**: PeopleList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PeopleListSlice = prismic.SharedSlice<
  "people_list",
  PeopleListSliceVariation
>;

/**
 * Primary content in *TitleButton → Default → Primary*
 */
export interface TitleButtonSliceDefaultPrimary {
  /**
   * Titre field in *TitleButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_button.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Lien field in *TitleButton → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: title_button.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  link: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * A droite ? field in *TitleButton → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: title_button.default.primary.reverse
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * Default variation for TitleButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleButton*
 */
type TitleButtonSliceVariation = TitleButtonSliceDefault;

/**
 * TitleButton Shared Slice
 *
 * - **API ID**: `title_button`
 * - **Description**: TitleButton
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleButtonSlice = prismic.SharedSlice<
  "title_button",
  TitleButtonSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      FullWidthImageSlice,
      FullWidthImageSliceDefaultPrimary,
      FullWidthImageSliceVariation,
      FullWidthImageSliceDefault,
      FullWidthImageTextButtonSlice,
      FullWidthImageTextButtonSliceDefaultPrimary,
      FullWidthImageTextButtonSliceVariation,
      FullWidthImageTextButtonSliceDefault,
      FullWidthTextSlice,
      FullWidthTextSliceDefaultPrimary,
      FullWidthTextSliceVariation,
      FullWidthTextSliceDefault,
      GradientSlice,
      GradientSliceDefaultPrimary,
      GradientSliceVariation,
      GradientSliceDefault,
      NewsListSlice,
      NewsListSliceDefaultPrimaryNewsItem,
      NewsListSliceDefaultPrimary,
      NewsListSliceVariation,
      NewsListSliceDefault,
      PeopleListSlice,
      PeopleListSliceDefaultPrimaryPeoplesItem,
      PeopleListSliceDefaultPrimary,
      PeopleListSliceVariation,
      PeopleListSliceDefault,
      TitleButtonSlice,
      TitleButtonSliceDefaultPrimary,
      TitleButtonSliceVariation,
      TitleButtonSliceDefault,
    };
  }
}
